### ISSUE TITLE
Make space, Enter, backspace and cursor work on Mobile

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#941]
This has waited long enough — let's improve the Carbon mobile experience!

### Tasks
- [x] Cursor should show up, blinking as it does on desktop
- [x] Make <kbd>Space</kbd> work appropriately, and not page down
- [x] Make <kbd>Enter</kbd> work appropriately
- [x] Ensure <kbd>Backspace</kbd> works appropriately

**Comment by mfix22** [comment]
If anyone comes across this and has more mobile issues, open a new issue! 👍
